#!/bin/sh
# File generated by ocamlbuild

cd /mnt/c/Users/emili/Documents/recocido

rm -f recocido.cmi
rm -f recocido.cmo
# Also clean the script itself
rm -f /mnt/c/Users/emili/Documents/recocido/_build/sanitize.sh
